"""Tests for redteam/report.py — Markdown rendering, no Supabase/network involved."""

import os

import pytest

from redteam.attacks.base import AttackResult
from redteam.report import BYPASS_CAP, CampaignMeta, generate


def _result(strategy, bypassed, response="[BLOCKED] L1 Regex match", errored=False, **metadata):
    return AttackResult(
        strategy=strategy,
        prompt=f"prompt for {strategy}",
        response=response,
        bypassed=bypassed,
        confidence=0.9,
        metadata=metadata,
        timestamp="2026-08-01T00:00:00+00:00",
        errored=errored,
    )


def _meta(**overrides):
    defaults = dict(
        campaign_id="test-campaign-id",
        target="http://localhost:8000/v1/chat/completions",
        date="2026-08-01T00:00:00+00:00",
        attacks=["template", "encoding", "pair"],
        fail_above=20.0,
    )
    defaults.update(overrides)
    return CampaignMeta(**defaults)


@pytest.fixture
def mixed_results():
    return [
        _result("template", False, response="[BLOCKED] L1 Regex match"),
        _result("template", True, response="Sure, here's how..."),
        _result("encoding", False, response="[BLOCKED] L2 DeBERTa injection"),
        _result("pair", True, response="Sure, here's the answer.", iterations_to_bypass=3),
        _result("pair", False, response="[BLOCKED] SessionGuard lockout"),
    ]


def test_all_section_headings_render(tmp_path, mixed_results):
    out = tmp_path / "report.md"
    md = generate(_meta(), mixed_results, str(out))

    for heading in [
        "# Aegis Red-Team Report",
        "## Executive Summary",
        "## Results by Strategy",
        "## Bypassed Prompts (Full Detail)",
        "## Blocked Attacks Summary",
        "## Recommendations",
        "Generated by Aegis",
    ]:
        assert heading in md


def test_writes_file_and_creates_parent_dirs(tmp_path, mixed_results):
    out = tmp_path / "nested" / "dir" / "report.md"
    generate(_meta(), mixed_results, str(out))
    assert out.exists()
    assert out.read_text(encoding="utf-8") != ""


def test_header_fields(tmp_path, mixed_results):
    md = generate(_meta(), mixed_results, str(tmp_path / "r.md"))
    assert "test-campaign-id" in md
    assert "http://localhost:8000/v1/chat/completions" in md
    assert "Total Attempts:** 5" in md


def test_bypass_cap_triggers_truncation_note(tmp_path):
    results = [_result("template", True, response=f"ok {i}") for i in range(BYPASS_CAP + 5)]
    md = generate(_meta(), results, str(tmp_path / "r.md"))
    assert f"Showing first {BYPASS_CAP} bypasses" in md
    assert md.count("### Bypass #") == BYPASS_CAP


def test_bypass_cap_not_triggered_under_limit(tmp_path):
    results = [_result("template", True, response=f"ok {i}") for i in range(3)]
    md = generate(_meta(), results, str(tmp_path / "r.md"))
    assert "Showing first" not in md
    assert md.count("### Bypass #") == 3


def test_recommendation_renders_only_when_template_bypassed(tmp_path):
    with_bypass = [_result("template", True), _result("encoding", False)]
    without_bypass = [_result("template", False), _result("encoding", False)]

    md_with = generate(_meta(), with_bypass, str(tmp_path / "a.md"))
    md_without = generate(_meta(), without_bypass, str(tmp_path / "b.md"))

    assert "Template attacks bypassed" in md_with
    assert "Template attacks bypassed" not in md_without


def test_recommendation_renders_only_when_encoding_bypassed(tmp_path):
    with_bypass = [_result("encoding", True), _result("template", False)]
    without_bypass = [_result("encoding", False), _result("template", False)]

    md_with = generate(_meta(), with_bypass, str(tmp_path / "a.md"))
    md_without = generate(_meta(), without_bypass, str(tmp_path / "b.md"))

    assert "Encoding attacks bypassed" in md_with
    assert "Encoding attacks bypassed" not in md_without


def test_recommendation_adaptive_vs_fixed_requires_pair_above_encoding(tmp_path):
    pair_wins = [_result("pair", True, iterations_to_bypass=2)] * 5 + [_result("encoding", False)] * 5
    pair_loses = [_result("pair", False)] * 5 + [_result("encoding", True)] * 5

    md_wins = generate(_meta(), pair_wins, str(tmp_path / "a.md"))
    md_loses = generate(_meta(), pair_loses, str(tmp_path / "b.md"))

    assert "Adaptive attacks significantly outperform" in md_wins
    assert "Adaptive attacks significantly outperform" not in md_loses


def test_recommendation_sessionguard_renders_when_pair_bypassed(tmp_path):
    with_bypass = [_result("pair", True, iterations_to_bypass=1)]
    without_bypass = [_result("pair", False)]

    md_with = generate(_meta(), with_bypass, str(tmp_path / "a.md"))
    md_without = generate(_meta(), without_bypass, str(tmp_path / "b.md"))

    assert "PAIR bypassed SessionGuard" in md_with
    assert "PAIR bypassed SessionGuard" not in md_without


def test_rerun_cadence_always_present(tmp_path, mixed_results):
    md = generate(_meta(), mixed_results, str(tmp_path / "r.md"))
    assert "Re-run cadence" in md


def test_footer_present(tmp_path, mixed_results):
    md = generate(_meta(), mixed_results, str(tmp_path / "r.md"))
    assert "Generated by Aegis" in md
    assert "Campaign ID: test-campaign-id | Target: http://localhost:8000/v1/chat/completions" in md


def test_executive_summary_pass_fail_wording(tmp_path):
    fails = [_result("pair", True) for _ in range(5)]  # 100% ASR > fail_above 20
    passes = [_result("pair", False) for _ in range(5)]  # 0% ASR <= 20

    md_fail = generate(_meta(fail_above=20.0), fails, str(tmp_path / "a.md"))
    md_pass = generate(_meta(fail_above=20.0), passes, str(tmp_path / "b.md"))

    assert "FAILED the configured threshold of 20.0%" in md_fail
    assert "PASSED the configured threshold of 20.0%" in md_pass


def test_errored_excluded_from_asr_and_blocked_counts(tmp_path):
    # errored rows are a separate outcome, previously double-counted as
    # "blocked" everywhere `not r.bypassed` was used as the blocked check
    # (executive summary, per-strategy table, blocked-attacks summary).
    # See PROJECT_DESC.md's error-handling audit.
    results = [
        _result("template", True, response="ok"),  # 1 real bypass
        _result("template", False, response="[BLOCKED] L1 Regex match"),  # 1 real block
        _result("template", False, response="[ERROR] ConnectError", errored=True),
        _result("encoding", False, response="[ERROR] ConnectError", errored=True),
    ]
    md = generate(_meta(), results, str(tmp_path / "r.md"))

    # Total attempts line still counts all 4 raw rows...
    assert "Total Attempts:** 4" in md
    # ...but the executive summary's scored ASR excludes the 2 errored rows:
    # 1 bypass out of 2 scored attempts = 50%, not 1/4 = 25%.
    assert "1 of 2 scored" in md
    assert "50.00%)" in md
    assert "2 attempts errored" in md
    # Results-by-strategy table: template row should show 1 bypass, 1
    # blocked, 1 error - not 2 blocked (which is what `not bypassed` would
    # have given before the fix).
    assert "| Template | 2 | 1 | 1 | 1 | 50.00% |" in md


def test_blocked_summary_excludes_errored(tmp_path):
    results = [
        _result("template", False, response="[BLOCKED] L1 Regex match"),
        _result("encoding", False, response="[ERROR] ConnectError", errored=True),
    ]
    md = generate(_meta(), results, str(tmp_path / "r.md"))
    assert "L1 Regex match" in md
    assert "ConnectError" not in md.split("## Blocked Attacks Summary")[1].split("##")[0]


def test_blocked_summary_reason_breakdown(tmp_path):
    results = [
        _result("template", False, response="[BLOCKED] L1 Regex match"),
        _result("template", False, response="[BLOCKED] L1 Regex match"),
        _result("encoding", False, response="[BLOCKED] L2 DeBERTa injection"),
    ]
    md = generate(_meta(), results, str(tmp_path / "r.md"))
    assert "L1 Regex match" in md
    assert "L2 DeBERTa injection" in md
